name: cl_test

channels:
  - anaconda
  - conda-forge

dependencies:
  - python>=3.8
  - pip
  - git
  - numba>0.54  # Better conda integration for compiled packages
  - dask

  - pip:
    - -e ../.[test]

